### ISSUE TITLE
Hexo内嵌网页踩坑记录 | nonlinearthink's blog

### ISSUE THREAD

**Issue by nonlinearthink** [nonlinearthink/nonlinearthink.github.io#15]
https://nonlinearthink.github.io/2020/07/09/hexo-iframe/ 

 首先，我先来说一说这个需求产生的原因，我前些日子更新了一些 CSS 相关的博客，但是我发现，要展示 CSS 的效果，必须要用到一些交互的功能，我必须要写一些小 demo，然后嵌入到网页中去。 一开始，我使用的就是纯粹的 HTML 代码，加上 style 和 script 标签，直接写在 .md 里面。 我意识到这不是一个好方法，一篇博客有时候需要多个 demo ，随着代码越来越多，每个 demo

**Comment by lemonly14** [comment]
试一试
