### ISSUE TITLE
CSS:单位计算与响应式布局 | nonlinearthink's blog

### ISSUE THREAD

**Issue by nonlinearthink** [nonlinearthink/nonlinearthink.github.io#2]
https://nonlinearthink.github.io/2020/07/01/css-unit-calculate/ 

 CSS中有很多的单位，大部分我们都不太用，我们的重点主要放在 px、em、rem、vh、vw 上面。 然后我们会稍微提及一下，响应式布局。  像素思维 这一小节，我们将介绍 px(Pixel)。  逻辑像素而不是物理像素 px 从字面上来看是像素的意思，很多新手一上来可能会认为它的物理像素。 这里必须要澄清，px一般是指逻辑像素，它会根据浏览器、操作系统、硬件设备做适当的缩放。 但是，通常96px

**Comment by nonlinearthink** [comment]
测试gittalk评论功能。

**Comment by wangtianyu0222** [comment]
$$
\mathbf X=\begin{pmatrix}
 x_{11}      & x_{12}       & \cdots & x_{1d}    &1   \\
 x_{21}       & x_{22}       & \cdots & x_{2d}     &1  \\
 \vdots & \vdots & \ddots & \vdots   & \vdots  \\
 x_{m1}       & x_{m2}       & \cdots & x_{md}   &1    \\
\end{pmatrix} = \begin{pmatrix}
\boldsymbol x_{1}^{\mathrm{T}}      & 1           \\
\boldsymbol x_{2}^{\mathrm{T}}       & 1           \\
 \vdots & \vdots   \\
\boldsymbol x_{m}^{\mathrm{T}}       & 1           \\
\end{pmatrix}
$$

**Comment by wangtianyu0222** [comment]
> @nonlinearthink
> 测试gittalk评论功能。

# 谢谢博主！
