### ISSUE TITLE
彻底理解 JDBC | nonlinearthink's blog

### ISSUE THREAD

**Issue by nonlinearthink** [nonlinearthink/nonlinearthink.github.io#3]
https://nonlinearthink.github.io/2020/06/27/jdbc-summary/ 

 JDBC (Java Database Connectivity) ，属于 Java 应用编程中比较基础的一块，我们会从最基本的开始，由浅入深地解释 JDBC 中的各种问题。  连接数据库  驱动初始化  基于 Class.forName 的初始化 想要开始 JDBC 编程，第一步是需要把 数据库驱动程序 的代码加载进来。 可以利用 Class.forName 函数，它原本的功能是返回一个 类或者

**Comment by wangtianyu0222** [comment]
# test
* dlnb!
** dlnb! **
