### ISSUE TITLE
使用 Vue-CLI 4 开发 Chrome扩展 | nonlinearthink's blog

### ISSUE THREAD

**Issue by nonlinearthink** [nonlinearthink/nonlinearthink.github.io#5]
https://nonlinearthink.github.io/2020/06/24/build-chrome-extension-vuecli4/ 

 网络上大部分Chrome插件开发的教程还停留在 Vue-CLI 2 的时代。导致我一开始想用 Vue 写 chrome扩展 的时候受到了深深的打击。 本文将使用 Vue-CLI 4 来做一个简单的 demo，包括 UI框架(以 Ant Design Vue 为例) 的导入。  创建 vue cli 4 项目 创建一个项目 1vue create demo 勾选 Babel、TypeScript、C

**Comment by rockey2020** [comment]
大佬没出现这个问题吗?https://github.com/superoo7/vue-cli-plugin-chrome-ext/issues/7

**Comment by nonlinearthink** [comment]
> @rockey2020
> 大佬没出现这个问题吗?https://github.com/superoo7/vue-cli-plugin-chrome-ext/issues/7

我写这篇文章的时候水平有限，如果这篇文章它不能工作，推荐去vue-cli ui的插件或者依赖选项里面搜chrome或者browser，我如果没记错，应该有更好的。

**Comment by rockey2020** [comment]
@nonlinearthink 没事谢谢啦 我用别的方式实现了这个插件的功能  用不用这个插件其实都无所谓
