### ISSUE TITLE
VSCode Python 运行环境配置 | nonlinearthink's blog

### ISSUE THREAD

**Issue by nonlinearthink** [nonlinearthink/nonlinearthink.github.io#6]
https://nonlinearthink.github.io/vscode/vscode-python/

 本期是小白向配置教程，大佬们请转身。  安装 Python 插件 需要安装的插件ID是 ms-python.python 。  为了防止小白弄不清楚，我放的是插件ID，不是名字，在 VSCode 插件中心搜索就行了。   配置 pythonPath VSCode 依赖于本地的命令行工具来运行 python代码。 Ctrl+Shift+P 打开命令面板，搜索 Preferences: Open Se

**Comment by lon91ong** [comment]
自带的jupyter插件使用的python环境和设置中用python.pythonpath所指定的不同
不知道该如何修改
请教

**Comment by nonlinearthink** [comment]
> @lon91ong
> 自带的jupyter插件使用的python环境和设置中用python.pythonpath所指定的不同
> 不知道该如何修改
> 请教

打开一个ipynb文件，注意一下左下角和右上角，左下角是python的环境，右上角是jupyter的环境，更改jupyter的环境需要下一个插件，你点击更改之后vscode会提示你安装。

**Comment by lon91ong** [comment]
> > @lon91ong
> > 自带的jupyter插件使用的python环境和设置中用python.pythonpath所指定的不同
> > 不知道该如何修改
> > 请教
> 
> 打开一个ipynb文件，注意一下左下角和右上角，左下角是python的环境，右上角是jupyter的环境，更改jupyter的环境需要下一个插件，你点击更改之后vscode会提示你安装。

多谢指点, 明白了! 
另外，更改Jupyter环境设置需要用到哪个插件呢? 给个关键词吧

**Comment by nonlinearthink** [comment]
> @lon91ong
> > > @lon91ong
> > > 自带的jupyter插件使用的python环境和设置中用python.pythonpath所指定的不同
> > > 不知道该如何修改
> > > 请教
> > 
> > 打开一个ipynb文件，注意一下左下角和右上角，左下角是python的环境，右上角是jupyter的环境，更改jupyter的环境需要下一个插件，你点击更改之后vscode会提示你安装。
> 
> 多谢指点, 明白了! 
> 另外，更改Jupyter环境设置需要用到哪个插件呢? 给个关键词吧

jupyter，搜插件id：ms-toolsai.jupyter

**Comment by lon91ong** [comment]
> > @lon91ong
> > > 
> > > 打开一个ipynb文件，注意一下左下角和右上角，左下角是python的环境，右上角是jupyter的环境，更改jupyter的环境需要下一个插件，你点击更改之后vscode会提示你安装。
> > 
> > 
> > 多谢指点, 明白了!
> > 另外，更改Jupyter环境设置需要用到哪个插件呢? 给个关键词吧
> 
> jupyter，搜插件id：ms-toolsai.jupyter

这个结果似乎不太对吧

![关键词搜索结果](https://user-images.githubusercontent.com/16462258/101981873-f952eb80-3caa-11eb-8297-d257b42dcde9.jpg)

**Comment by nonlinearthink** [comment]
> @lon91ong
> > > @lon91ong
> > > > 
> > > > 打开一个ipynb文件，注意一下左下角和右上角，左下角是python的环境，右上角是jupyter的环境，更改jupyter的环境需要下一个插件，你点击更改之后vscode会提示你安装。
> > > 
> > > 
> > > 多谢指点, 明白了!
> > > 另外，更改Jupyter环境设置需要用到哪个插件呢? 给个关键词吧
> > 
> > jupyter，搜插件id：ms-toolsai.jupyter
> 
> 这个结果似乎不太对吧，怎么我已经默认安装了呢？
> 
> ![关键词搜索结果](https://user-images.githubusercontent.com/16462258/101981873-f952eb80-3caa-11eb-8297-d257b42dcde9.jpg)
> 

那你估计可以换了

**Comment by lon91ong** [comment]
@nonlinearthink  
> 那你估计可以换了

看了两圈也只找到这个和Python环境相关的设置
![相关设置项](https://user-images.githubusercontent.com/16462258/101981995-b80f0b80-3cab-11eb-9ad8-06a45da1ca44.jpg)

**Comment by nonlinearthink** [comment]
> @nonlinearthink
> 
> > 那你估计可以换了
> 
> 看了两圈也只找到这个和Python环境相关的设置
> 只能关闭自动搜索环境，没有给出手动配置的选项
> ![相关设置项](https://user-images.githubusercontent.com/16462258/101981995-b80f0b80-3cab-11eb-9ad8-06a45da1ca44.jpg)

嗯，主要点击左下角和右上角那里就可以换了，不用去改配置文件。
