### ISSUE TITLE
hexo-butterfly评论系统配置: Gittalk | nonlinearthink's blog

### ISSUE THREAD

**Issue by nonlinearthink** [nonlinearthink/nonlinearthink.github.io#9]
https://nonlinearthink.github.io/2020/07/08/hexo-gittalk/#%E6%9B%B4%E6%96%B0-%E5%8F%91%E5%B8%83 

 本文将介绍 hexo 博客配置 Gittalk 评论系统，我使用的主题是 hexo-butterfly ，已经支持 Gittalk 配置，我的网页部署在 Github Pages 上面，如果你使用 Gitee 或者 云服务器 ，有些参数修改的时候要注意。  Gittalk 简介 Gittalk 是一个评论系统，它的原理是借助 GitHub Issue 的评论功能，来存储和管理评论。 像是 disq

**Comment by ayqming** [comment]
写的很好啊，我来第一个留言吧。

**Comment by qinjinbnu** [comment]
## 我来试试

```
貌似很不错 我也弄一个

```

**Comment by l0ganc** [comment]
Test

**Comment by jiftle** [comment]
test comment function.

**Comment by jiftle** [comment]
评论仓库需要手工建立吗

**Comment by nonlinearthink** [comment]
> 评论仓库需要手工建立吗

评论仓库只会用到issue功能，自己建或者用你现成的仓库都可以，我是直接用放我这个网页的那个仓库。

**Comment by lemon-lollipop** [comment]
我整合gitalk  只显示     上面那个   蓝色双虚线 和 “评论” 那俩字儿 ，下面的评论区不加载。    实在整不好了，楼主求指教

**Comment by nonlinearthink** [comment]
> @lemon-lollipop
> 我整合gitalk  只显示     上面那个   蓝色双虚线 和 “评论” 那俩字儿 ，下面的评论区不加载。    实在整不好了，楼主求指教
> 
我几天前刚更新过，你看看是不是最后那个butterfly 3.0的问题。我前几天电脑重装后，下了3.0似乎也是你那个情况。

**Comment by crossyourheart** [comment]
找到错误了，偷懒复制了错误的信息 Gittalk ，多了个t

**Comment by nonlinearthink** [comment]
> @crossyourheart
> 找到错误了，偷懒复制了错误的信息 Gittalk ，多了个t 

我的锅，打错了

**Comment by crossyourheart** [comment]
再请教下， 怎么让顶部显示背景图片。  顶部默认是被蓝色覆盖的，  我设置了 theme_color: main: 是可以修改颜色。 不知咋能把这个蓝色Banner 变成透明

**Comment by nonlinearthink** [comment]
> @crossyourheart
> 再请教下， 怎么让顶部显示背景图片。  顶部默认是被蓝色覆盖的，  我设置了 theme_color: main: 是可以修改颜色。 不知咋能把这个蓝色Banner 变成透明

文章中显示图片的话，在写文章的时候在meta信息里加`cover: 图片链接`。

**Comment by aaaaaajie** [comment]
大赞 解决了 我的问题

**Comment by XYCode-XYC** [comment]
我来试试
